server:
  port: 80
  tomcat:
    uri-encoding: utf-8
user:
  password:
    #密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  messages:
    #国际化资源文件路径
    basename: i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: druid
  http:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  devtools:
    restart:
      enabled: true    
# MyBatis
mybatis:
    # 配置类型别名
    typeAliasesPackage: com.ruoyi.project.system.user.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath:mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml