#flyway会自动建立该数据库
db:
    # mysql, oracle, sqlserver
    type: mysql
    name: framework_jpa
    username: root
    password: root
# 数据源配置
spring:
    datasource:
        master:
            type: com.zaxxer.hikari.HikariDataSource
            driverClassName: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://localhost:3306/${db.name}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
            username: ${db.username}
            password: ${db.password}
        slave:
            enabled: false
            type: com.zaxxer.hikari.HikariDataSource
            driverClassName: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://localhost:3306/${db.name}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
            username: ${db.username}
            password: ${db.password}

    flyway:
        enabled: true
        url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        user: ${db.username}
        password: ${db.password}
        #目标数据库已经存在，不自动升级
        baseline-on-migrate: false
        encoding: utf-8
        clean-on-validation-error: false
        clean-disabled: true
        #数据库自动迁移的位置
        locations: classpath:db/migration/${db.type}
        # 需要管理的数据库
        schemas: ${db.name}
        sql-migration-prefix: v