wechat:
  cp:
    corpId: wwffb70143e94111eb
    appConfigs:
      - agentId: 999999
        secret: yeL6mZp5IFIkfQ3wWMGFI8G-L4a6BEF194fnRzhvCy0
        token: 111
        aesKey: 111
      - agentId: 1000002
        secret: 1111
        token: 111
        aesKey: 111
  pay:
    appId: #微信公众号或者小程序等的appid
    mchId: #微信支付商户号
    mchKey: #微信支付商户密钥
    subAppId: #服务商模式下的子商户公众账号ID
    subMchId: #服务商模式下的子商户号
    keyPath: # p12证书的位置，可以指定绝对路径，也可以指定类路径（以classpath:开头）